# Generated by Django 3.0.5 on 2020-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(max_length=3)),
                ('category', models.CharField(choices=[('TR', 'Trailer'), ('FU', 'Furgoneta'), ('LO', 'Lona')], default='TR', max_length=2)),
                ('state', models.CharField(choices=[('FR', 'Free'), ('OC', 'Occupied')], default='FR', max_length=2)),
            ],
        ),
    ]
