# Generated by Django 3.0.5 on 2020-04-05 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TR', 'Trailer'), ('FU', 'Furgoneta'), ('LO', 'Camión de lona')], default='TR', max_length=2)),
                ('state', models.CharField(choices=[('FR', 'Libre'), ('OC', 'Ocupado')], default='FR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='TimeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activity', models.CharField(choices=[('CA', 'Carga'), ('DE', 'Descarga'), ('ND', 'No disponible')], max_length=2)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.Dock')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.Order')),
                ('time_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.TimeSegment')),
            ],
        ),
    ]
