# Generated by Django 3.0.5 on 2020-04-08 22:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TR', 'Trailer'), ('VA', 'Van'), ('TT', 'Tarpaulin truck')], default='TR', max_length=2)),
                ('state', models.CharField(choices=[('FR', 'Free'), ('OC', 'Occupied')], default='FR', max_length=2)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,6}$', 'Order can only contain numbers.')])),
                ('activity', models.CharField(choices=[('LO', 'Load'), ('UL', 'Unload')], default='LO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DockActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('LO', 'Load'), ('UL', 'Unload'), ('UA', 'Unavailable')], max_length=2)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.Dock')),
                ('time_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.TimeSegment')),
            ],
            options={
                'verbose_name_plural': 'Dock activities',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\w{1,15}$', 'License plate can only contain numbers and letters.')])),
                ('dock_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.DockActivity', unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.Order', unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dockactivity',
            constraint=models.UniqueConstraint(fields=('dock', 'time_segment'), name='unique_activity'),
        ),
    ]
