# Generated by Django 3.0.5 on 2020-04-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activity',
            field=models.CharField(choices=[('LO', 'Load'), ('UL', 'Unload')], default='Unload', max_length=2),
            preserve_default=False,
        ),
    ]
