# Generated by Django 3.0.5 on 2020-04-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dock_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dock',
            options={'ordering': ['number']},
        ),
    ]
