# Generated by Django 3.0.4 on 2020-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='number',
            field=models.SmallIntegerField(),
        ),
    ]
