# Generated by Django 3.0.5 on 2020-04-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dock_scheduler', '0002_auto_20200405_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesegment',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='timesegment',
            name='dock',
        ),
        migrations.AlterField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.Order', unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.TimeSegment', unique=True),
        ),
        migrations.AlterField(
            model_name='dock',
            name='category',
            field=models.CharField(choices=[('TR', 'Trailer'), ('VA', 'Van'), ('CA', 'Tarpaulin truck')], default='TR', max_length=2),
        ),
        migrations.AlterField(
            model_name='dock',
            name='state',
            field=models.CharField(choices=[('FR', 'Free'), ('OC', 'Occupied')], default='FR', max_length=2),
        ),
        migrations.CreateModel(
            name='DockActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('CA', 'Carga'), ('DE', 'Descarga'), ('ND', 'No disponible')], max_length=2)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.Dock')),
                ('time_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.TimeSegment')),
            ],
        ),
    ]
