# Generated by Django 3.0.5 on 2020-04-04 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dock_scheduler', '0002_auto_20200404_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='TimeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('activity', models.CharField(choices=[('CA', 'Carga'), ('DE', 'Descarga'), ('ND', 'No disponible')], max_length=2)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.Dock')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=15)),
                ('time_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.TimeSegment')),
            ],
        ),
    ]
