# Generated by Django 3.0.5 on 2020-04-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dock_scheduler', '0003_auto_20200405_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dockactivity',
            options={'verbose_name_plural': 'Dock activities'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dock_scheduler.DockActivity', unique=True),
        ),
        migrations.AddConstraint(
            model_name='dockactivity',
            constraint=models.UniqueConstraint(fields=('dock', 'time_segment'), name='unique_activity'),
        ),
    ]
