# Generated by Django 3.0.5 on 2020-04-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dock_scheduler', '0004_auto_20200405_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time_segment',
            new_name='dock_activity',
        ),
    ]
