# Generated by Django 3.0.5 on 2020-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dock_scheduler', '0005_auto_20200405_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockactivity',
            name='activity',
            field=models.CharField(choices=[('CA', 'Load'), ('DE', 'Unload'), ('ND', 'Unavailable')], max_length=2),
        ),
    ]
